start
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 20:48:18' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 20:48:19' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
java.sql.SQLException: Field 'address' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddUser(Connector.java:171)
	at Command.getOutput(Command.java:28)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
java.sql.SQLException: Field 'address' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddUser(Connector.java:171)
	at Command.getOutput(Command.java:28)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
java.sql.SQLException: Field 'address' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddUser(Connector.java:171)
	at Command.getOutput(Command.java:28)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-20" java.lang.ArrayIndexOutOfBoundsException: 2
	at Command.getOutput(Command.java:67)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:05:56' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.google.android.gcm.server.InvalidRequestException: HTTP Status Code: 503(<HTML>
<HEAD>
<TITLE>Service Unavailable</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Service Unavailable</H1>
<H2>Error 503</H2>
</BODY>
</HTML>)
	at com.google.android.gcm.server.Sender.sendNoRetry(Sender.java:367)
	at com.google.android.gcm.server.Sender.send(Sender.java:261)
	at Command.MessageToClient(Command.java:281)
	at Command.getOutput(Command.java:76)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:09:49' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:11:45' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:19:19' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-36" java.lang.ArrayIndexOutOfBoundsException: 3
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:30:10' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:30:11' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:41:38' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:44:35' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:44:40' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'Login-2013-04-06 21:44:44' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.SendMessage(Connector.java:265)
	at Command.getOutput(Command.java:74)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-45" java.lang.ArrayIndexOutOfBoundsException: 2
	at Command.getOutput(Command.java:67)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'task_ID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'task_ID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''tttttt, NOW())' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'task_ID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column '596412F0' in 'field list'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '113-3 9 23:16:30' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'Thu Apr 11 23:20:30 EDT 2013' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: ' 113- 3-10 23:21:30' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '0113-03-11 23:27:30' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '20113-03-11 23:28:30' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-131" java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:447)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:340)
	at Command.getOutput(Command.java:105)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-132" java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:447)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:340)
	at Command.getOutput(Command.java:105)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-133" java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:447)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:340)
	at Command.getOutput(Command.java:105)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Column 'task_ID' cannot be null
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddTask(Connector.java:337)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
java.sql.SQLException: Field 'address' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddUser(Connector.java:171)
	at Command.getOutput(Command.java:28)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '3913-04-19 15:36' for column 'due_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2983)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.AddGroupTask(Connector.java:424)
	at Command.getOutput(Command.java:97)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-109" java.lang.ArrayIndexOutOfBoundsException: 2
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-110" java.lang.ArrayIndexOutOfBoundsException: 2
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-113" java.lang.ArrayIndexOutOfBoundsException: 2
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-144" java.lang.NumberFormatException: For input string: "161365913477"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-162" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-164" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-165" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-174" java.lang.NumberFormatException: For input string: "161366429083"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-177" java.lang.NumberFormatException: For input string: "221366429518"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-180" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-183" java.lang.NumberFormatException: For input string: "161366531473"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-184" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-186" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-189" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-190" java.lang.NumberFormatException: For input string: "161366411158"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:459)
	at java.lang.Integer.parseInt(Integer.java:497)
	at Connector.DeleteTask(Connector.java:427)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'F715450D96614853ADAC87366F9C1578' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column '69FFF550B1F442BBB853E8E4E0138716' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'D282908FCB4D4040B4C09939C5965E5D' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'C4660ED7E8114167AC7ACB1BB128A1D5' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column '13554B661B9B496788AE6DBD458DEA80' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'F715450D96614853ADAC87366F9C1578' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'C4660ED7E8114167AC7ACB1BB128A1D5' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 'D282908FCB4D4040B4C09939C5965E5D' in 'where clause'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteTask(Connector.java:437)
	at Command.getOutput(Command.java:113)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= 17' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= 17' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= 17' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= '17'' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= '17'' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= 17' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group WHERE group_ID= 17' at line 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
	at com.mysql.jdbc.Statement.execute(Statement.java:727)
	at Connector.execute(Connector.java:69)
	at Connector.DeleteGroup(Connector.java:443)
	at Command.getOutput(Command.java:137)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-36" java.lang.ArrayIndexOutOfBoundsException: 1
	at Command.getOutput(Command.java:153)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-37" java.lang.ArrayIndexOutOfBoundsException: 1
	at Command.getOutput(Command.java:153)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-38" java.lang.ArrayIndexOutOfBoundsException: 1
	at Command.getOutput(Command.java:153)
	at ProviderHandler.run(ProviderHandler.java:44)
	at java.lang.Thread.run(Thread.java:637)
Exception in thread "Thread-179" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-181" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-182" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-183" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-185" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-186" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-187" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-209" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-212" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-213" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-214" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-216" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-219" java.lang.ArrayIndexOutOfBoundsException
